FROM nginx
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Copia los certificados desde el backend hacia el contenedor de Nginx
#COPY ./wildcard/star_idartes_gov_co.crt /etc/nginx/certificates/
#COPY ./wildcard/star_idartes_gov_co.key /etc/nginx/certificates/
#COPY ./wildcard/DigiCertCA.crt /etc/nginx/certificates/
