<?php

return [
    // Tipos de via
    ['category' => 'road_type', 'name' => 'Calle',        'alias' => 'CL',   'code' => 'CL'],
    ['category' => 'road_type', 'name' => 'Carrera',      'alias' => 'CR',   'code' => 'CR'],
    ['category' => 'road_type', 'name' => 'Avenida',      'alias' => 'AV',   'code' => 'AV'],
    ['category' => 'road_type', 'name' => 'Avenida Calle','alias' => 'AC',   'code' => 'AC'],
    ['category' => 'road_type', 'name' => 'Avenida Carrera','alias' => 'AK', 'code' => 'AK'],
    ['category' => 'road_type', 'name' => 'Diagonal',     'alias' => 'DG',   'code' => 'DG'],
    ['category' => 'road_type', 'name' => 'Transversal',  'alias' => 'TV',   'code' => 'TV'],
    ['category' => 'road_type', 'name' => 'Circular',     'alias' => 'CIR',  'code' => 'CIR'],
    ['category' => 'road_type', 'name' => 'Autopista',    'alias' => 'AUT',  'code' => 'AUT'],
    ['category' => 'road_type', 'name' => 'Vía',          'alias' => 'VIA',  'code' => 'VIA'],

    // Letras
    ['category' => 'letter', 'name' => 'A', 'alias' => 'A', 'code' => 'A'],
    ['category' => 'letter', 'name' => 'B', 'alias' => 'B', 'code' => 'B'],
    ['category' => 'letter', 'name' => 'C', 'alias' => 'C', 'code' => 'C'],
    ['category' => 'letter', 'name' => 'D', 'alias' => 'D', 'code' => 'D'],
    ['category' => 'letter', 'name' => 'E', 'alias' => 'E', 'code' => 'E'],
    ['category' => 'letter', 'name' => 'F', 'alias' => 'F', 'code' => 'F'],
    ['category' => 'letter', 'name' => 'G', 'alias' => 'G', 'code' => 'G'],
    ['category' => 'letter', 'name' => 'H', 'alias' => 'H', 'code' => 'H'],
    ['category' => 'letter', 'name' => 'I', 'alias' => 'I', 'code' => 'I'],
    ['category' => 'letter', 'name' => 'J', 'alias' => 'J', 'code' => 'J'],
    ['category' => 'letter', 'name' => 'K', 'alias' => 'K', 'code' => 'K'],
    ['category' => 'letter', 'name' => 'L', 'alias' => 'L', 'code' => 'L'],
    ['category' => 'letter', 'name' => 'M', 'alias' => 'M', 'code' => 'M'],
    ['category' => 'letter', 'name' => 'N', 'alias' => 'N', 'code' => 'N'],
    ['category' => 'letter', 'name' => 'O', 'alias' => 'O', 'code' => 'O'],
    ['category' => 'letter', 'name' => 'P', 'alias' => 'P', 'code' => 'P'],
    ['category' => 'letter', 'name' => 'Q', 'alias' => 'Q', 'code' => 'Q'],
    ['category' => 'letter', 'name' => 'R', 'alias' => 'R', 'code' => 'R'],
    ['category' => 'letter', 'name' => 'S', 'alias' => 'S', 'code' => 'S'],
    ['category' => 'letter', 'name' => 'T', 'alias' => 'T', 'code' => 'T'],
    ['category' => 'letter', 'name' => 'U', 'alias' => 'U', 'code' => 'U'],
    ['category' => 'letter', 'name' => 'V', 'alias' => 'V', 'code' => 'V'],
    ['category' => 'letter', 'name' => 'W', 'alias' => 'W', 'code' => 'W'],
    ['category' => 'letter', 'name' => 'X', 'alias' => 'X', 'code' => 'X'],
    ['category' => 'letter', 'name' => 'Y', 'alias' => 'Y', 'code' => 'Y'],
    ['category' => 'letter', 'name' => 'Z', 'alias' => 'Z', 'code' => 'Z'],
    ['category' => 'letter', 'name' => 'BIS', 'alias' => 'BIS', 'code' => 'BIS'],

    // Orientación
    ['category' => 'orientation', 'name' => 'Norte', 'alias' => 'N',  'code' => 'N'],
    ['category' => 'orientation', 'name' => 'Sur', 'alias' => 'S',  'code' => 'S'],
    ['category' => 'orientation', 'name' => 'Este', 'alias' => 'E',  'code' => 'E'],
    ['category' => 'orientation', 'name' => 'Oeste', 'alias' => 'O',  'code' => 'O'],
    ['category' => 'orientation', 'name' => 'Nororiente', 'alias' => 'NE', 'code' => 'NE'],
    ['category' => 'orientation', 'name' => 'Noroccidente','alias' => 'NO', 'code' => 'NO'],
    ['category' => 'orientation', 'name' => 'Suroriente',  'alias' => 'SE', 'code' => 'SE'],
    ['category' => 'orientation', 'name' => 'Suroccidente','alias' => 'SO', 'code' => 'SO'],

    ['category' => 'stratum', 'name' => 'Estrato 1', 'alias' => '1', 'code' => '1'],
    ['category' => 'stratum', 'name' => 'Estrato 2', 'alias' => '2', 'code' => '2'],
    ['category' => 'stratum', 'name' => 'Estrato 3', 'alias' => '3', 'code' => '3'],
    ['category' => 'stratum', 'name' => 'Estrato 4', 'alias' => '4', 'code' => '4'],
    ['category' => 'stratum', 'name' => 'Estrato 5', 'alias' => '5', 'code' => '5'],
    ['category' => 'stratum', 'name' => 'Estrato 6', 'alias' => '6', 'code' => '6'],
];
