<?php

return [
    ['category' => 'economic_activity', 'name' => 'Asalariados', 'alias' => null, 'code' => '0010'],
    ['category' => 'economic_activity', 'name' => 'Sin actividad económica, solo para personas naturales', 'alias' => null, 'code' => '0081'],
    ['category' => 'economic_activity', 'name' => 'Personas Naturales Subsidiadas por Terceros', 'alias' => null, 'code' => '0082'],
    ['category' => 'economic_activity', 'name' => 'Rentistas de Capital, solo para personas naturales', 'alias' => null, 'code' => '0090'],
    ['category' => 'economic_activity', 'name' => 'Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas', 'alias' => null, 'code' => '0111'],
    ['category' => 'economic_activity', 'name' => 'Cultivo de arroz', 'alias' => null, 'code' => '0112'],
    ['category' => 'economic_activity', 'name' => 'Cultivo de hortalizas, raíces y tubérculos', 'alias' => null, 'code' => '0113'],
    ['category' => 'economic_activity', 'name' => 'Cultivo de tabaco', 'alias' => null, 'code' => '0114'],
    ['category' => 'economic_activity', 'name' => 'Cultivo de plantas textiles', 'alias' => null, 'code' => '0115'],
    ['category' => 'economic_activity', 'name' => 'Otros cultivos transitorios n.c.p.', 'alias' => null, 'code' => '0119'],
    ['category' => 'economic_activity', 'name' => 'Cultivo de frutas tropicales y subtropicales', 'alias' => null, 'code' => '0121'],
    ['category' => 'economic_activity', 'name' => 'Cultivo de plátano y banano', 'alias' => null, 'code' => '0122'],
    ['category' => 'economic_activity', 'name' => 'Cultivo de café', 'alias' => null, 'code' => '0123'],
    ['category' => 'economic_activity', 'name' => 'Cultivo de caña de azúcar', 'alias' => null, 'code' => '0124'],
    ['category' => 'economic_activity', 'name' => 'Cultivo de flor de corte', 'alias' => null, 'code' => '0125'],
    ['category' => 'economic_activity', 'name' => 'Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos', 'alias' => null, 'code' => '0126'],
    ['category' => 'economic_activity', 'name' => 'Cultivo de plantas con las que se preparan bebidas', 'alias' => null, 'code' => '0127'],
    ['category' => 'economic_activity', 'name' => 'Cultivo de especias y de plantas aromáticas y medicinales', 'alias' => null, 'code' => '0128'],
    ['category' => 'economic_activity', 'name' => 'Otros cultivos permanentes n.c.p.', 'alias' => null, 'code' => '0129'],
    ['category' => 'economic_activity', 'name' => 'Propagación de plantas (actividades de los viveros, excepto viveros forestales)', 'alias' => null, 'code' => '0130'],
    ['category' => 'economic_activity', 'name' => 'Cría de ganado bovino y bufalino', 'alias' => null, 'code' => '0141'],
    ['category' => 'economic_activity', 'name' => 'Cría de caballos y otros equinos', 'alias' => null, 'code' => '0142'],
    ['category' => 'economic_activity', 'name' => 'Cría de ovejas y cabras', 'alias' => null, 'code' => '0143'],
    ['category' => 'economic_activity', 'name' => 'Cría de ganado porcino', 'alias' => null, 'code' => '0144'],
    ['category' => 'economic_activity', 'name' => 'Cría de aves de corral', 'alias' => null, 'code' => '0145'],
    ['category' => 'economic_activity', 'name' => 'Cría de otros animales n.c.p.', 'alias' => null, 'code' => '0149'],
    ['category' => 'economic_activity', 'name' => 'Actividades de apoyo a la agricultura', 'alias' => null, 'code' => '0161'],
    ['category' => 'economic_activity', 'name' => 'Actividades de apoyo a la ganadería', 'alias' => null, 'code' => '0162'],
    ['category' => 'economic_activity', 'name' => 'Actividades posteriores a la cosecha', 'alias' => null, 'code' => '0163'],
    ['category' => 'economic_activity', 'name' => 'Tratamiento de semillas para propagación', 'alias' => null, 'code' => '0164'],
    ['category' => 'economic_activity', 'name' => 'Silvicultura y otras actividades forestales', 'alias' => null, 'code' => '0210'],
    ['category' => 'economic_activity', 'name' => 'Extracción de madera', 'alias' => null, 'code' => '0220'],
    ['category' => 'economic_activity', 'name' => 'Recolección de productos forestales diferentes a la madera', 'alias' => null, 'code' => '0230'],
    ['category' => 'economic_activity', 'name' => 'Pesca marítima', 'alias' => null, 'code' => '0311'],
    ['category' => 'economic_activity', 'name' => 'Pesca de agua dulce', 'alias' => null, 'code' => '0312'],
    ['category' => 'economic_activity', 'name' => 'Acuicultura marítima', 'alias' => null, 'code' => '0321'],
    ['category' => 'economic_activity', 'name' => 'Acuicultura de agua dulce', 'alias' => null, 'code' => '0322'],
    ['category' => 'economic_activity', 'name' => 'Extracción de hulla (carbón de piedra)', 'alias' => null, 'code' => '0510'],
    ['category' => 'economic_activity', 'name' => 'Extracción de carbón lignito', 'alias' => null, 'code' => '0520'],
    ['category' => 'economic_activity', 'name' => 'Extracción de petróleo crudo', 'alias' => null, 'code' => '0610'],
    ['category' => 'economic_activity', 'name' => 'Extracción de gas natural', 'alias' => null, 'code' => '0620'],
    ['category' => 'economic_activity', 'name' => 'Extracción de minerales de hierro', 'alias' => null, 'code' => '0710'],
    ['category' => 'economic_activity', 'name' => 'Extracción de minerales de uranio y de torio', 'alias' => null, 'code' => '0721'],
    ['category' => 'economic_activity', 'name' => 'Extracción de oro y otros metales preciosos', 'alias' => null, 'code' => '0722'],
    ['category' => 'economic_activity', 'name' => 'Extracción de minerales de níquel', 'alias' => null, 'code' => '0723'],
    ['category' => 'economic_activity', 'name' => 'Extracción de otros minerales metalíferos no ferrosos n.c.p.', 'alias' => null, 'code' => '0729'],
    ['category' => 'economic_activity', 'name' => 'Extracción de piedra, arena, arcillas comunes, yeso y anhidrita', 'alias' => null, 'code' => '0811'],
    ['category' => 'economic_activity', 'name' => 'Extracción de arcillas de uso industrial, Caliza, Caolín y Bentonitas', 'alias' => null, 'code' => '0812'],
    ['category' => 'economic_activity', 'name' => 'Extracción de esmeraldas, piedras preciosas y semipreciosas', 'alias' => null, 'code' => '0820'],
    ['category' => 'economic_activity', 'name' => 'Extracción de minerales para la fabricación de abonos y productos químicos', 'alias' => null, 'code' => '0891'],
    ['category' => 'economic_activity', 'name' => 'Extracción de halita (sal)', 'alias' => null, 'code' => '0892'],
    ['category' => 'economic_activity', 'name' => 'Extracción de otros minerales no metálicos n.c.p.', 'alias' => null, 'code' => '0899'],
    ['category' => 'economic_activity', 'name' => 'Actividades de apoyo para la extracción de petróleo y de gas natural', 'alias' => null, 'code' => '0910'],
    ['category' => 'economic_activity', 'name' => 'Actividades de apoyo para otras actividades de explotación de minas y canteras', 'alias' => null, 'code' => '0990'],
    ['category' => 'economic_activity', 'name' => 'Procesamiento y conservación de carne y productos cárnicos', 'alias' => null, 'code' => '1011'],
    ['category' => 'economic_activity', 'name' => 'Procesamiento y conservación de pescados, crustáceos y moluscos', 'alias' => null, 'code' => '1012'],
    ['category' => 'economic_activity', 'name' => 'Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos', 'alias' => null, 'code' => '1020'],
    ['category' => 'economic_activity', 'name' => 'Elaboración de aceites y grasas de origen vegetal y animal', 'alias' => null, 'code' => '1030'],
    ['category' => 'economic_activity', 'name' => 'Elaboración de productos lácteos', 'alias' => null, 'code' => '1040'],
    ['category' => 'economic_activity', 'name' => 'Elaboración de productos de molinería', 'alias' => null, 'code' => '1051'],
    ['category' => 'economic_activity', 'name' => 'Elaboración de almidones y productos derivados del almidón', 'alias' => null, 'code' => '1052'],
    ['category' => 'economic_activity', 'name' => 'Trilla de café', 'alias' => null, 'code' => '1061'],
    ['category' => 'economic_activity', 'name' => 'Descafeinado, tostión y molienda del café', 'alias' => null, 'code' => '1062'],
    ['category' => 'economic_activity', 'name' => 'Otros derivados del café', 'alias' => null, 'code' => '1063'],
    ['category' => 'economic_activity', 'name' => 'Elaboración y refinación de azúcar', 'alias' => null, 'code' => '1071'],
    ['category' => 'economic_activity', 'name' => 'Elaboración de panela', 'alias' => null, 'code' => '1072'],
    ['category' => 'economic_activity', 'name' => 'Elaboración de productos de panadería', 'alias' => null, 'code' => '1081'],
    ['category' => 'economic_activity', 'name' => 'Elaboración de cacao, chocolate y productos de confitería', 'alias' => null, 'code' => '1082'],
    ['category' => 'economic_activity', 'name' => 'Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares', 'alias' => null, 'code' => '1083'],
    ['category' => 'economic_activity', 'name' => 'Elaboración de comidas y platos preparados', 'alias' => null, 'code' => '1084'],
    ['category' => 'economic_activity', 'name' => 'Elaboración de otros productos alimenticios n.c.p.', 'alias' => null, 'code' => '1089'],
    ['category' => 'economic_activity', 'name' => 'Elaboración de alimentos preparados para animales', 'alias' => null, 'code' => '1090'],
    ['category' => 'economic_activity', 'name' => 'Destilación, rectificación y mezcla de bebidas alcohólicas', 'alias' => null, 'code' => '1101'],
    ['category' => 'economic_activity', 'name' => 'Elaboración de bebidas fermentadas no destiladas', 'alias' => null, 'code' => '1102'],
    ['category' => 'economic_activity', 'name' => 'Producción de malta, elaboración de cervezas y otras bebidas malteadas producción de aguas minerales', 'alias' => null, 'code' => '1103'],
    ['category' => 'economic_activity', 'name' => 'Elaboración de productos del tabaco', 'alias' => null, 'code' => '1200'],
    ['category' => 'economic_activity', 'name' => 'Preparación e Hilatura de fibras textiles', 'alias' => null, 'code' => '1311'],
    ['category' => 'economic_activity', 'name' => 'Tejeduría de productos textiles', 'alias' => null, 'code' => '1312'],
    ['category' => 'economic_activity', 'name' => 'Acabado de productos textiles', 'alias' => null, 'code' => '1313'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de tejidos de punto y ganchillo', 'alias' => null, 'code' => '1391'],
    ['category' => 'economic_activity', 'name' => 'Confección de artículos con materiales textiles, excepto prendas de vestir', 'alias' => null, 'code' => '1392'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de tapetes y alfombras para pisos', 'alias' => null, 'code' => '1393'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de otros artículos textiles n.c.p.', 'alias' => null, 'code' => '1399'],
    ['category' => 'economic_activity', 'name' => 'Confección de prendas de vestir, excepto prendas de piel', 'alias' => null, 'code' => '1410'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de artículos de punto y ganchillo', 'alias' => null, 'code' => '1430'],
    ['category' => 'economic_activity', 'name' => 'Curtido y recurtido de cueros, recurtido y teñido de pieles', 'alias' => null, 'code' => '1511'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería', 'alias' => null, 'code' => '1512'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de artículos de viaje, bolsos de mano y artículos similares; artículos de talabartería y guarnicionería elaborados en otros materiales', 'alias' => null, 'code' => '1513'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de calzado de cuero y piel, con cualquier tipo de suela', 'alias' => null, 'code' => '1521'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de otros tipos de calzado, excepto calzado de cuero y piel', 'alias' => null, 'code' => '1522'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de partes del calzado', 'alias' => null, 'code' => '1523'],
    ['category' => 'economic_activity', 'name' => 'Aserrado, acepillado e impregnación de la madera', 'alias' => null, 'code' => '1610'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles', 'alias' => null, 'code' => '1620'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción', 'alias' => null, 'code' => '1630'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de recipientes de madera', 'alias' => null, 'code' => '1640'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería', 'alias' => null, 'code' => '1690'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de pulpas (pastas) celulósicas, papel y cartón', 'alias' => null, 'code' => '1701'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón', 'alias' => null, 'code' => '1702'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de otros artículos de papel y cartón', 'alias' => null, 'code' => '1709'],
    ['category' => 'economic_activity', 'name' => 'Actividades de impresión', 'alias' => null, 'code' => '1811'],
    ['category' => 'economic_activity', 'name' => 'Actividades de servicios relacionados con la impresión', 'alias' => null, 'code' => '1812'],
    ['category' => 'economic_activity', 'name' => 'Producción de copias a partir de grabaciones originales', 'alias' => null, 'code' => '1820'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de productos de hornos de coque', 'alias' => null, 'code' => '1910'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de productos de la refinación del petróleo', 'alias' => null, 'code' => '1921'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de sustancias y productos químicos básicos', 'alias' => null, 'code' => '2011'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de abonos y compuestos inorgánicos nitrogenados', 'alias' => null, 'code' => '2012'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de plásticos en formas primarias', 'alias' => null, 'code' => '2013'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de caucho sintético en formas primarias', 'alias' => null, 'code' => '2014'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario', 'alias' => null, 'code' => '2021'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas', 'alias' => null, 'code' => '2022'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador', 'alias' => null, 'code' => '2023'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de otros productos químicos n.c.p.', 'alias' => null, 'code' => '2029'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de fibras sintéticas y artificiales', 'alias' => null, 'code' => '2030'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico', 'alias' => null, 'code' => '2100'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de llantas y neumáticos de caucho', 'alias' => null, 'code' => '2211'],
    ['category' => 'economic_activity', 'name' => 'Reencauche de llantas usadas', 'alias' => null, 'code' => '2212'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.', 'alias' => null, 'code' => '2219'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de formas básicas de plástico', 'alias' => null, 'code' => '2221'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de artículos de plástico n.c.p.', 'alias' => null, 'code' => '2229'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de vidrio y productos de vidrio', 'alias' => null, 'code' => '2310'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de productos refractarios', 'alias' => null, 'code' => '2391'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de materiales de arcilla para la construcción', 'alias' => null, 'code' => '2392'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de otros productos de cerámica y porcelana', 'alias' => null, 'code' => '2393'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de cemento, cal y yeso', 'alias' => null, 'code' => '2394'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de artículos de hormigón, cemento y yeso', 'alias' => null, 'code' => '2395'],
    ['category' => 'economic_activity', 'name' => 'Corte, tallado y acabado de la piedra', 'alias' => null, 'code' => '2396'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de otros productos minerales no metálicos n.c.p.', 'alias' => null, 'code' => '2399'],
    ['category' => 'economic_activity', 'name' => 'Industrias básicas de hierro y de acero', 'alias' => null, 'code' => '2410'],
    ['category' => 'economic_activity', 'name' => 'Industrias básicas de metales preciosos', 'alias' => null, 'code' => '2421'],
    ['category' => 'economic_activity', 'name' => 'Industrias básicas de otros metales no ferrosos', 'alias' => null, 'code' => '2429'],
    ['category' => 'economic_activity', 'name' => 'Fundición de hierro y de acero', 'alias' => null, 'code' => '2431'],
    ['category' => 'economic_activity', 'name' => 'Fundición de metales no ferrosos', 'alias' => null, 'code' => '2432'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de productos metálicos para uso estructural', 'alias' => null, 'code' => '2511'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías', 'alias' => null, 'code' => '2512'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central', 'alias' => null, 'code' => '2513'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de armas y municiones', 'alias' => null, 'code' => '2520'],
    ['category' => 'economic_activity', 'name' => 'Forja, prensado, estampado y laminado de metal; pulvimetalurgia trabajos de ingeniería mecánica en general realizados a cambio de una retribución o por contrata', 'alias' => null, 'code' => '2591'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería', 'alias' => null, 'code' => '2593'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de otros productos elaborados de metal n.c.p.', 'alias' => null, 'code' => '2599'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de componentes y tableros electrónicos', 'alias' => null, 'code' => '2610'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de computadoras y de equipo periférico', 'alias' => null, 'code' => '2620'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de equipos de comunicación', 'alias' => null, 'code' => '2630'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de aparatos electrónicos de consumo', 'alias' => null, 'code' => '2640'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de equipo de medición, prueba, navegación y control', 'alias' => null, 'code' => '2651'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de relojes', 'alias' => null, 'code' => '2652'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico', 'alias' => null, 'code' => '2660'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de instrumentos ópticos y equipo fotográfico', 'alias' => null, 'code' => '2670'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de medios magnéticos y ópticos para almacenamiento de datos', 'alias' => null, 'code' => '2680'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de motores, generadores y transformadores eléctricos', 'alias' => null, 'code' => '2711'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de aparatos de distribución y control de la energía eléctrica', 'alias' => null, 'code' => '2712'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de pilas, baterías y acumuladores eléctricos', 'alias' => null, 'code' => '2720'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de hilos y cables eléctricos y de fibra óptica', 'alias' => null, 'code' => '2731'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de dispositivos de cableado', 'alias' => null, 'code' => '2732'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de equipos eléctricos de iluminación', 'alias' => null, 'code' => '2740'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de aparatos de uso doméstico', 'alias' => null, 'code' => '2750'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de otros tipos de equipo eléctrico n.c.p.', 'alias' => null, 'code' => '2790'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de motores, turbinas, y partes para motores de combustión interna', 'alias' => null, 'code' => '2811'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de equipos de potencia hidráulica y neumática', 'alias' => null, 'code' => '2812'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de otras bombas, compresores, grifos y válvulas', 'alias' => null, 'code' => '2813'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión', 'alias' => null, 'code' => '2814'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de hornos, hogares y quemadores industriales', 'alias' => null, 'code' => '2815'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de equipo de elevación y manipulación', 'alias' => null, 'code' => '2816'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)', 'alias' => null, 'code' => '2817'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de herramientas manuales con motor', 'alias' => null, 'code' => '2818'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p..', 'alias' => null, 'code' => '2819'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de maquinaria agropecuaria y forestal', 'alias' => null, 'code' => '2821'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de máquinas formadoras de metal y de máquinas herramienta', 'alias' => null, 'code' => '2822'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de maquinaria para la metalurgia', 'alias' => null, 'code' => '2823'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción', 'alias' => null, 'code' => '2824'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco', 'alias' => null, 'code' => '2825'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros', 'alias' => null, 'code' => '2826'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.', 'alias' => null, 'code' => '2829'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de vehículos automotores y sus motores fabricación de remolques y semirremolques', 'alias' => null, 'code' => '2910'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores', 'alias' => null, 'code' => '2930'],
    ['category' => 'economic_activity', 'name' => 'Construcción de barcos y de estructuras flotantes', 'alias' => null, 'code' => '3011'],
    ['category' => 'economic_activity', 'name' => 'Construcción de embarcaciones de recreo y deporte', 'alias' => null, 'code' => '3012'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de locomotoras y de material rodante para ferrocarriles', 'alias' => null, 'code' => '3020'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de aeronaves, naves espaciales y de maquinaria conexa', 'alias' => null, 'code' => '3030'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de vehículos militares de combate', 'alias' => null, 'code' => '3040'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de motocicletas', 'alias' => null, 'code' => '3091'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad', 'alias' => null, 'code' => '3092'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de otros tipos de equipo de transporte n.c.p.', 'alias' => null, 'code' => '3099'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de muebles', 'alias' => null, 'code' => '3110'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de colchones y somieres', 'alias' => null, 'code' => '3120'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de joyas, bisutería y artículos conexos', 'alias' => null, 'code' => '3210'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de instrumentos musicales', 'alias' => null, 'code' => '3220'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de artículos y equipo para la práctica del deporte', 'alias' => null, 'code' => '3230'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de juegos, juguetes y rompecabezas', 'alias' => null, 'code' => '3240'],
    ['category' => 'economic_activity', 'name' => 'Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario)', 'alias' => null, 'code' => '3250'],
    ['category' => 'economic_activity', 'name' => 'Otras industrias manufactureras n.c.p. fabricación de artículos de piel', 'alias' => null, 'code' => '3290'],
    ['category' => 'economic_activity', 'name' => 'Mantenimiento y reparación especializado de productos elaborados en metal', 'alias' => null, 'code' => '3311'],
    ['category' => 'economic_activity', 'name' => 'Mantenimiento y reparación especializado de maquinaria y equipo', 'alias' => null, 'code' => '3312'],
    ['category' => 'economic_activity', 'name' => 'Mantenimiento y reparación especializado de equipo electrónico y óptico', 'alias' => null, 'code' => '3313'],
    ['category' => 'economic_activity', 'name' => 'Mantenimiento y reparación especializado de equipo eléctrico', 'alias' => null, 'code' => '3314'],
    ['category' => 'economic_activity', 'name' => 'Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas', 'alias' => null, 'code' => '3315'],
    ['category' => 'economic_activity', 'name' => 'Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.', 'alias' => null, 'code' => '3319'],
    ['category' => 'economic_activity', 'name' => 'Instalación especializada de maquinaria y equipo industrial', 'alias' => null, 'code' => '3320'],
    ['category' => 'economic_activity', 'name' => 'Generación de energía eléctrica', 'alias' => null, 'code' => '3511'],
    ['category' => 'economic_activity', 'name' => 'Transmisión de energía eléctrica', 'alias' => null, 'code' => '3512'],
    ['category' => 'economic_activity', 'name' => 'Distribución de energía eléctrica', 'alias' => null, 'code' => '3513'],
    ['category' => 'economic_activity', 'name' => 'Comercialización de energía eléctrica', 'alias' => null, 'code' => '3514'],
    ['category' => 'economic_activity', 'name' => 'Producción de gas, distribución de combustibles gaseosos por tuberías.', 'alias' => null, 'code' => '3520'],
    ['category' => 'economic_activity', 'name' => 'Suministro de vapor y aire acondicionado', 'alias' => null, 'code' => '3530'],
    ['category' => 'economic_activity', 'name' => 'Captación, tratamiento y distribución de agua', 'alias' => null, 'code' => '3600'],
    ['category' => 'economic_activity', 'name' => 'Evacuación y tratamiento de aguas residuales', 'alias' => null, 'code' => '3700'],
    ['category' => 'economic_activity', 'name' => 'Recolección de desechos no peligrosos', 'alias' => null, 'code' => '3811'],
    ['category' => 'economic_activity', 'name' => 'Recolección de desechos peligrosos', 'alias' => null, 'code' => '3812'],
    ['category' => 'economic_activity', 'name' => 'Tratamiento y disposición de desechos no peligrosos', 'alias' => null, 'code' => '3821'],
    ['category' => 'economic_activity', 'name' => 'Tratamiento y disposición de desechos peligrosos', 'alias' => null, 'code' => '3822'],
    ['category' => 'economic_activity', 'name' => 'Recuperación de materiales', 'alias' => null, 'code' => '3830'],
    ['category' => 'economic_activity', 'name' => 'Actividades de saneamiento ambiental y otros servicios de gestión de desechos', 'alias' => null, 'code' => '3900'],
    ['category' => 'economic_activity', 'name' => 'Construcción de edificios residenciales', 'alias' => null, 'code' => '4111'],
    ['category' => 'economic_activity', 'name' => 'Construcción de edificios no residenciales', 'alias' => null, 'code' => '4112'],
    ['category' => 'economic_activity', 'name' => 'Construcción de carreteras y vías de ferrocarril', 'alias' => null, 'code' => '4210'],
    ['category' => 'economic_activity', 'name' => 'Construcción de proyectos de servicio público', 'alias' => null, 'code' => '4220'],
    ['category' => 'economic_activity', 'name' => 'Construcción de otras obras de ingeniería civil', 'alias' => null, 'code' => '4290'],
    ['category' => 'economic_activity', 'name' => 'Demolición', 'alias' => null, 'code' => '4311'],
    ['category' => 'economic_activity', 'name' => 'Preparación del terreno', 'alias' => null, 'code' => '4312'],
    ['category' => 'economic_activity', 'name' => 'Instalaciones eléctricas', 'alias' => null, 'code' => '4321'],
    ['category' => 'economic_activity', 'name' => 'Instalaciones de fontanería, calefacción y aire acondicionado', 'alias' => null, 'code' => '4322'],
    ['category' => 'economic_activity', 'name' => 'Otras instalaciones especializadas', 'alias' => null, 'code' => '4329'],
    ['category' => 'economic_activity', 'name' => 'Terminación y acabado de edificios y obras de ingeniería civil', 'alias' => null, 'code' => '4330'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil', 'alias' => null, 'code' => '4390'],
    ['category' => 'economic_activity', 'name' => 'Comercio de vehículos automotores nuevos', 'alias' => null, 'code' => '4511'],
    ['category' => 'economic_activity', 'name' => 'Comercio de vehículos automotores usados', 'alias' => null, 'code' => '4512'],
    ['category' => 'economic_activity', 'name' => 'Mantenimiento y reparación de vehículos automotores', 'alias' => null, 'code' => '4520'],
    ['category' => 'economic_activity', 'name' => 'Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores', 'alias' => null, 'code' => '4530'],
    ['category' => 'economic_activity', 'name' => 'Comercio de motocicletas y de sus partes, piezas y accesorios', 'alias' => null, 'code' => '4541'],
    ['category' => 'economic_activity', 'name' => 'Mantenimiento y reparación de motocicletas y de sus partes y piezas', 'alias' => null, 'code' => '4542'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor a cambio de una retribución o por contrata', 'alias' => null, 'code' => '4610'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de materias primas agropecuarias; animales vivos.', 'alias' => null, 'code' => '4620'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de productos alimenticios', 'alias' => null, 'code' => '4631'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de bebidas y tabaco', 'alias' => null, 'code' => '4632'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico', 'alias' => null, 'code' => '4641'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de prendas de vestir', 'alias' => null, 'code' => '4642'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de calzado', 'alias' => null, 'code' => '4643'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de aparatos y equipo de uso doméstico', 'alias' => null, 'code' => '4644'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador', 'alias' => null, 'code' => '4645'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de otros utensilios domésticos n.c.p.', 'alias' => null, 'code' => '4649'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de computadores, equipo periférico y programas de informática', 'alias' => null, 'code' => '4651'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones', 'alias' => null, 'code' => '4652'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.', 'alias' => null, 'code' => '4659'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos', 'alias' => null, 'code' => '4661'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de metales y productos metalíferos', 'alias' => null, 'code' => '4662'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción', 'alias' => null, 'code' => '4663'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario', 'alias' => null, 'code' => '4664'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de desperdicios, desechos y chatarra', 'alias' => null, 'code' => '4665'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor de otros productos n.c.p.', 'alias' => null, 'code' => '4669'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por mayor no especializado', 'alias' => null, 'code' => '4690'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco', 'alias' => null, 'code' => '4711'],
    ['category' => 'economic_activity', 'name' => 'Comercio a por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas y tabaco', 'alias' => null, 'code' => '4719'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados', 'alias' => null, 'code' => '4721'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de leche, productos lácteos y huevos en establecimientos especializados', 'alias' => null, 'code' => '4722'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar en establecimientos especializados', 'alias' => null, 'code' => '4723'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de bebidas y productos de tabaco, en establecimientos especializados', 'alias' => null, 'code' => '4724'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados', 'alias' => null, 'code' => '4729'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de combustible para automotores', 'alias' => null, 'code' => '4731'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de lubricantes (aceites y grasas) aditivos y productos de limpieza para vehículos automotores', 'alias' => null, 'code' => '4732'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados', 'alias' => null, 'code' => '4741'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados', 'alias' => null, 'code' => '4742'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de productos textiles en establecimientos especializados', 'alias' => null, 'code' => '4751'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados', 'alias' => null, 'code' => '4752'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de tapices, alfombras y recubrimientos para paredes y pisos en establecimientos especializados', 'alias' => null, 'code' => '4753'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de electrodomésticos y gasodomesticos de uso doméstico, muebles y equipos de iluminación', 'alias' => null, 'code' => '4754'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de artículos y utensilios de uso doméstico', 'alias' => null, 'code' => '4755'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de otros artículos domésticos en establecimientos especializados', 'alias' => null, 'code' => '4759'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados', 'alias' => null, 'code' => '4761'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de artículos deportivos, en establecimientos especializados', 'alias' => null, 'code' => '4762'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados', 'alias' => null, 'code' => '4769'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados', 'alias' => null, 'code' => '4771'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados.', 'alias' => null, 'code' => '4772'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados', 'alias' => null, 'code' => '4773'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de otros productos nuevos, en establecimientos especializados', 'alias' => null, 'code' => '4774'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de artículos de segunda mano', 'alias' => null, 'code' => '4775'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de alimentos, bebidas y tabaco en puestos de venta móviles', 'alias' => null, 'code' => '4781'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles', 'alias' => null, 'code' => '4782'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor de otros productos, en puestos de venta móviles', 'alias' => null, 'code' => '4789'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor realizado a través de Internet', 'alias' => null, 'code' => '4791'],
    ['category' => 'economic_activity', 'name' => 'Comercio al por menor realizado a través de casas de venta o por correo', 'alias' => null, 'code' => '4792'],
    ['category' => 'economic_activity', 'name' => 'Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados', 'alias' => null, 'code' => '4799'],
    ['category' => 'economic_activity', 'name' => 'Transporte férreo de pasajeros', 'alias' => null, 'code' => '4911'],
    ['category' => 'economic_activity', 'name' => 'Transporte férreo de carga', 'alias' => null, 'code' => '4912'],
    ['category' => 'economic_activity', 'name' => 'Transporte de pasajeros', 'alias' => null, 'code' => '4921'],
    ['category' => 'economic_activity', 'name' => 'Transporte mixto', 'alias' => null, 'code' => '4922'],
    ['category' => 'economic_activity', 'name' => 'Transporte de carga por carretera', 'alias' => null, 'code' => '4923'],
    ['category' => 'economic_activity', 'name' => 'Transporte por tuberías', 'alias' => null, 'code' => '4930'],
    ['category' => 'economic_activity', 'name' => 'Transporte de pasajeros marítimo y de cabotaje', 'alias' => null, 'code' => '5011'],
    ['category' => 'economic_activity', 'name' => 'Transporte de carga marítimo y de cabotaje', 'alias' => null, 'code' => '5012'],
    ['category' => 'economic_activity', 'name' => 'Transporte fluvial de pasajeros', 'alias' => null, 'code' => '5021'],
    ['category' => 'economic_activity', 'name' => 'Transporte fluvial de carga', 'alias' => null, 'code' => '5022'],
    ['category' => 'economic_activity', 'name' => 'Transporte aéreo nacional de pasajeros', 'alias' => null, 'code' => '5111'],
    ['category' => 'economic_activity', 'name' => 'Transporte aéreo internacional de pasajeros', 'alias' => null, 'code' => '5112'],
    ['category' => 'economic_activity', 'name' => 'Transporte aéreo nacional de carga', 'alias' => null, 'code' => '5121'],
    ['category' => 'economic_activity', 'name' => 'Transporte aéreo internacional de carga', 'alias' => null, 'code' => '5122'],
    ['category' => 'economic_activity', 'name' => 'Almacenamiento y depósito', 'alias' => null, 'code' => '5210'],
    ['category' => 'economic_activity', 'name' => 'Actividades de estaciones, vías y servicios complementarios para el transporte terrestre', 'alias' => null, 'code' => '5221'],
    ['category' => 'economic_activity', 'name' => 'Actividades de puertos y servicios complementarios para el transporte acuático', 'alias' => null, 'code' => '5222'],
    ['category' => 'economic_activity', 'name' => 'Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo', 'alias' => null, 'code' => '5223'],
    ['category' => 'economic_activity', 'name' => 'Manipulación de carga', 'alias' => null, 'code' => '5224'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades complementarias al transporte', 'alias' => null, 'code' => '5229'],
    ['category' => 'economic_activity', 'name' => 'Actividades postales nacionales', 'alias' => null, 'code' => '5310'],
    ['category' => 'economic_activity', 'name' => 'Actividades de mensajería', 'alias' => null, 'code' => '5320'],
    ['category' => 'economic_activity', 'name' => 'Alojamiento en hoteles', 'alias' => null, 'code' => '5511'],
    ['category' => 'economic_activity', 'name' => 'Alojamiento en aparta-hoteles', 'alias' => null, 'code' => '5512'],
    ['category' => 'economic_activity', 'name' => 'Alojamiento en centros vacacionales', 'alias' => null, 'code' => '5513'],
    ['category' => 'economic_activity', 'name' => 'Alojamiento rural', 'alias' => null, 'code' => '5514'],
    ['category' => 'economic_activity', 'name' => 'Otros tipos de alojamientos para visitantes', 'alias' => null, 'code' => '5519'],
    ['category' => 'economic_activity', 'name' => 'Actividades de zonas de camping y parques para vehículos recreacionales', 'alias' => null, 'code' => '5520'],
    ['category' => 'economic_activity', 'name' => 'Servicios por horas', 'alias' => null, 'code' => '5530'],
    ['category' => 'economic_activity', 'name' => 'Otros tipos de alojamiento n.c.p.', 'alias' => null, 'code' => '5590'],
    ['category' => 'economic_activity', 'name' => 'Expendio a la mesa de comidas preparadas', 'alias' => null, 'code' => '5611'],
    ['category' => 'economic_activity', 'name' => 'Expendio por autoservicio de comidas preparadas', 'alias' => null, 'code' => '5612'],
    ['category' => 'economic_activity', 'name' => 'Expendio de comidas preparadas en cafeterías', 'alias' => null, 'code' => '5613'],
    ['category' => 'economic_activity', 'name' => 'Otros tipos de expendio de comidas preparadas n.c.p.', 'alias' => null, 'code' => '5619'],
    ['category' => 'economic_activity', 'name' => 'Catering para eventos', 'alias' => null, 'code' => '5621'],
    ['category' => 'economic_activity', 'name' => 'Actividades de otros servicios de comidas', 'alias' => null, 'code' => '5629'],
    ['category' => 'economic_activity', 'name' => 'Expendio de bebidas alcohólicas para el consumo dentro del establecimiento', 'alias' => null, 'code' => '5630'],
    ['category' => 'economic_activity', 'name' => 'Edición de libros', 'alias' => null, 'code' => '5811'],
    ['category' => 'economic_activity', 'name' => 'Edición de directorios y listas de correo', 'alias' => null, 'code' => '5812'],
    ['category' => 'economic_activity', 'name' => 'Edición de periódicos, revistas y otras publicaciones periódicas', 'alias' => null, 'code' => '5813'],
    ['category' => 'economic_activity', 'name' => 'Otros trabajos de edición', 'alias' => null, 'code' => '5819'],
    ['category' => 'economic_activity', 'name' => 'Edición de programas de informática (software)', 'alias' => null, 'code' => '5820'],
    ['category' => 'economic_activity', 'name' => 'Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión', 'alias' => null, 'code' => '5911'],
    ['category' => 'economic_activity', 'name' => 'Actividades de postproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión', 'alias' => null, 'code' => '5912'],
    ['category' => 'economic_activity', 'name' => 'Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión', 'alias' => null, 'code' => '5913'],
    ['category' => 'economic_activity', 'name' => 'Actividades de exhibición de películas cinematográficas y videos', 'alias' => null, 'code' => '5914'],
    ['category' => 'economic_activity', 'name' => 'Actividades de grabación de sonido y edición de música', 'alias' => null, 'code' => '5920'],
    ['category' => 'economic_activity', 'name' => 'Actividades de programación y transmisión en el servicio de radiodifusión sonora', 'alias' => null, 'code' => '6010'],
    ['category' => 'economic_activity', 'name' => 'Actividades de programación y transmisión de televisión', 'alias' => null, 'code' => '6020'],
    ['category' => 'economic_activity', 'name' => 'Actividades de telecomunicaciones alámbricas', 'alias' => null, 'code' => '6110'],
    ['category' => 'economic_activity', 'name' => 'Actividades de telecomunicaciones inalámbricas', 'alias' => null, 'code' => '6120'],
    ['category' => 'economic_activity', 'name' => 'Actividades de telecomunicación satelital', 'alias' => null, 'code' => '6130'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades de telecomunicaciones', 'alias' => null, 'code' => '6190'],
    ['category' => 'economic_activity', 'name' => 'Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas).', 'alias' => null, 'code' => '6201'],
    ['category' => 'economic_activity', 'name' => 'Actividades de consultoría informática y actividades de administración de instalaciones informáticas', 'alias' => null, 'code' => '6202'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades de tecnologías de información y actividades de servicios informáticos', 'alias' => null, 'code' => '6209'],
    ['category' => 'economic_activity', 'name' => 'Procesamiento de datos, alojamiento (hosting) y actividades relacionadas', 'alias' => null, 'code' => '6311'],
    ['category' => 'economic_activity', 'name' => 'Portales Web', 'alias' => null, 'code' => '6312'],
    ['category' => 'economic_activity', 'name' => 'Actividades de agencias de noticias', 'alias' => null, 'code' => '6391'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades de servicio de información n.c.p.', 'alias' => null, 'code' => '6399'],
    ['category' => 'economic_activity', 'name' => 'Banco Central', 'alias' => null, 'code' => '6411'],
    ['category' => 'economic_activity', 'name' => 'Bancos comerciales', 'alias' => null, 'code' => '6412'],
    ['category' => 'economic_activity', 'name' => 'Actividades de las corporaciones financieras', 'alias' => null, 'code' => '6421'],
    ['category' => 'economic_activity', 'name' => 'Actividades de las compañías de financiamiento', 'alias' => null, 'code' => '6422'],
    ['category' => 'economic_activity', 'name' => 'Banca de segundo piso', 'alias' => null, 'code' => '6423'],
    ['category' => 'economic_activity', 'name' => 'Actividades de las cooperativas financieras', 'alias' => null, 'code' => '6424'],
    ['category' => 'economic_activity', 'name' => 'Fideicomisos, fondos y entidades financieras similares', 'alias' => null, 'code' => '6431'],
    ['category' => 'economic_activity', 'name' => 'Fondos de cesantías', 'alias' => null, 'code' => '6432'],
    ['category' => 'economic_activity', 'name' => 'Leasing financiero (arrendamiento financiero)', 'alias' => null, 'code' => '6491'],
    ['category' => 'economic_activity', 'name' => 'Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario', 'alias' => null, 'code' => '6492'],
    ['category' => 'economic_activity', 'name' => 'Actividades de compra de cartera o factoring', 'alias' => null, 'code' => '6493'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades de distribución de fondos', 'alias' => null, 'code' => '6494'],
    ['category' => 'economic_activity', 'name' => 'Instituciones especiales oficiales', 'alias' => null, 'code' => '6495'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p.', 'alias' => null, 'code' => '6499'],
    ['category' => 'economic_activity', 'name' => 'Seguros generales', 'alias' => null, 'code' => '6511'],
    ['category' => 'economic_activity', 'name' => 'Seguros de vida', 'alias' => null, 'code' => '6512'],
    ['category' => 'economic_activity', 'name' => 'Reaseguros', 'alias' => null, 'code' => '6513'],
    ['category' => 'economic_activity', 'name' => 'Capitalización', 'alias' => null, 'code' => '6514'],
    ['category' => 'economic_activity', 'name' => 'Servicios de seguros sociales de salud', 'alias' => null, 'code' => '6521'],
    ['category' => 'economic_activity', 'name' => 'Servicios de seguros sociales de riesgos profesionales', 'alias' => null, 'code' => '6522'],
    ['category' => 'economic_activity', 'name' => 'Régimen de prima media con prestación definida (RPM)', 'alias' => null, 'code' => '6531'],
    ['category' => 'economic_activity', 'name' => 'Régimen de ahorro individual (RAI).', 'alias' => null, 'code' => '6532'],
    ['category' => 'economic_activity', 'name' => 'Administración de mercados financieros', 'alias' => null, 'code' => '6611'],
    ['category' => 'economic_activity', 'name' => 'Corretaje de valores y de contratos de productos básicos', 'alias' => null, 'code' => '6612'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades relacionadas con el mercado de valores', 'alias' => null, 'code' => '6613'],
    ['category' => 'economic_activity', 'name' => 'Actividades de las casas de cambio', 'alias' => null, 'code' => '6614'],
    ['category' => 'economic_activity', 'name' => 'Actividades de los profesionales de compra y venta de divisas', 'alias' => null, 'code' => '6615'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades auxiliares de las actividades de servicios financieros n.c.p', 'alias' => null, 'code' => '6619'],
    ['category' => 'economic_activity', 'name' => 'Actividades de agentes y corredores de seguros', 'alias' => null, 'code' => '6621'],
    ['category' => 'economic_activity', 'name' => 'Evaluación de riesgos y daños y otras actividades de servicios auxiliares', 'alias' => null, 'code' => '6629'],
    ['category' => 'economic_activity', 'name' => 'Actividades de administración de fondos', 'alias' => null, 'code' => '6630'],
    ['category' => 'economic_activity', 'name' => 'Actividades inmobiliarias realizadas con bienes propios o arrendados', 'alias' => null, 'code' => '6810'],
    ['category' => 'economic_activity', 'name' => 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata', 'alias' => null, 'code' => '6820'],
    ['category' => 'economic_activity', 'name' => 'Actividades jurídicas', 'alias' => null, 'code' => '6910'],
    ['category' => 'economic_activity', 'name' => 'Actividades de contabilidad, teneduría de libros, auditoria financiera y asesoría tributaria', 'alias' => null, 'code' => '6920'],
    ['category' => 'economic_activity', 'name' => 'Actividades de administración empresarial', 'alias' => null, 'code' => '7010'],
    ['category' => 'economic_activity', 'name' => 'Actividades de consultoría de gestión', 'alias' => null, 'code' => '7020'],
    ['category' => 'economic_activity', 'name' => 'Actividades de arquitectura e ingeniería y otras actividades conexas de consultoría técnica', 'alias' => null, 'code' => '7110'],
    ['category' => 'economic_activity', 'name' => 'Ensayos y análisis técnicos', 'alias' => null, 'code' => '7120'],
    ['category' => 'economic_activity', 'name' => 'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería', 'alias' => null, 'code' => '7210'],
    ['category' => 'economic_activity', 'name' => 'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades', 'alias' => null, 'code' => '7220'],
    ['category' => 'economic_activity', 'name' => 'Publicidad', 'alias' => null, 'code' => '7310'],
    ['category' => 'economic_activity', 'name' => 'Estudios de mercado y realización de encuestas de opinión pública', 'alias' => null, 'code' => '7320'],
    ['category' => 'economic_activity', 'name' => 'Actividades especializadas de diseño', 'alias' => null, 'code' => '7410'],
    ['category' => 'economic_activity', 'name' => 'Actividades de fotografía', 'alias' => null, 'code' => '7420'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades profesionales, científicas y técnicas n.c.p.', 'alias' => null, 'code' => '7490'],
    ['category' => 'economic_activity', 'name' => 'Actividades veterinarias', 'alias' => null, 'code' => '7500'],
    ['category' => 'economic_activity', 'name' => 'Alquiler y arrendamiento de vehículos automotores', 'alias' => null, 'code' => '7710'],
    ['category' => 'economic_activity', 'name' => 'Alquiler y arrendamiento de equipo recreativo y deportivo', 'alias' => null, 'code' => '7721'],
    ['category' => 'economic_activity', 'name' => 'Alquiler de videos y discos', 'alias' => null, 'code' => '7722'],
    ['category' => 'economic_activity', 'name' => 'Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.', 'alias' => null, 'code' => '7729'],
    ['category' => 'economic_activity', 'name' => 'Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.', 'alias' => null, 'code' => '7730'],
    ['category' => 'economic_activity', 'name' => 'Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor', 'alias' => null, 'code' => '7740'],
    ['category' => 'economic_activity', 'name' => 'Actividades de agencias de empleo', 'alias' => null, 'code' => '7810'],
    ['category' => 'economic_activity', 'name' => 'Actividades de agencias de empleo temporal', 'alias' => null, 'code' => '7820'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades de suministro de recurso humano', 'alias' => null, 'code' => '7830'],
    ['category' => 'economic_activity', 'name' => 'Actividades de las agencias de viajes', 'alias' => null, 'code' => '7911'],
    ['category' => 'economic_activity', 'name' => 'Actividades de operadores turísticos', 'alias' => null, 'code' => '7912'],
    ['category' => 'economic_activity', 'name' => 'Otros servicios de reserva y actividades relacionadas', 'alias' => null, 'code' => '7990'],
    ['category' => 'economic_activity', 'name' => 'Actividades de seguridad privada', 'alias' => null, 'code' => '8010'],
    ['category' => 'economic_activity', 'name' => 'Actividades de servicios de sistemas de seguridad', 'alias' => null, 'code' => '8020'],
    ['category' => 'economic_activity', 'name' => 'Actividades de detectives e investigadores privados', 'alias' => null, 'code' => '8030'],
    ['category' => 'economic_activity', 'name' => 'Actividades combinadas de apoyo a instalaciones', 'alias' => null, 'code' => '8110'],
    ['category' => 'economic_activity', 'name' => 'Limpieza general interior de edificios', 'alias' => null, 'code' => '8121'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades de limpieza de edificios e instalaciones industriales', 'alias' => null, 'code' => '8129'],
    ['category' => 'economic_activity', 'name' => 'Actividades de paisajismo y servicios de mantenimiento conexos', 'alias' => null, 'code' => '8130'],
    ['category' => 'economic_activity', 'name' => 'Actividades combinadas de servicios administrativos de oficina', 'alias' => null, 'code' => '8211'],
    ['category' => 'economic_activity', 'name' => 'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina', 'alias' => null, 'code' => '8219'],
    ['category' => 'economic_activity', 'name' => 'Actividades de centros de llamadas (Call center)', 'alias' => null, 'code' => '8220'],
    ['category' => 'economic_activity', 'name' => 'Organización de convenciones y eventos comerciales', 'alias' => null, 'code' => '8230'],
    ['category' => 'economic_activity', 'name' => 'Actividades de agencias de cobranza y oficinas de calificación crediticia', 'alias' => null, 'code' => '8291'],
    ['category' => 'economic_activity', 'name' => 'Actividades de envase y empaque', 'alias' => null, 'code' => '8292'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades de servicio de apoyo a las empresas n.c.p.', 'alias' => null, 'code' => '8299'],
    ['category' => 'economic_activity', 'name' => 'Actividades legislativas de la administración publica', 'alias' => null, 'code' => '8411'],
    ['category' => 'economic_activity', 'name' => 'Actividades ejecutivas de la administración publica', 'alias' => null, 'code' => '8412'],
    ['category' => 'economic_activity', 'name' => 'Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social', 'alias' => null, 'code' => '8413'],
    ['category' => 'economic_activity', 'name' => 'Actividades reguladoras y facilitadoras de la actividad económica', 'alias' => null, 'code' => '8414'],
    ['category' => 'economic_activity', 'name' => 'Actividades de los otros órganos de control', 'alias' => null, 'code' => '8415'],
    ['category' => 'economic_activity', 'name' => 'Relaciones exteriores', 'alias' => null, 'code' => '8421'],
    ['category' => 'economic_activity', 'name' => 'Actividades de defensa', 'alias' => null, 'code' => '8422'],
    ['category' => 'economic_activity', 'name' => 'Orden público y actividades de seguridad', 'alias' => null, 'code' => '8423'],
    ['category' => 'economic_activity', 'name' => 'Administración de justicia', 'alias' => null, 'code' => '8424'],
    ['category' => 'economic_activity', 'name' => 'Actividades de planes de seguridad social de afiliación obligatoria', 'alias' => null, 'code' => '8430'],
    ['category' => 'economic_activity', 'name' => 'Educación preescolar', 'alias' => null, 'code' => '8512'],
    ['category' => 'economic_activity', 'name' => 'Educación básica primaria', 'alias' => null, 'code' => '8513'],
    ['category' => 'economic_activity', 'name' => 'Educación básica secundaria', 'alias' => null, 'code' => '8521'],
    ['category' => 'economic_activity', 'name' => 'Educación media académica', 'alias' => null, 'code' => '8522'],
    ['category' => 'economic_activity', 'name' => 'Educación media técnica y de formación laboral', 'alias' => null, 'code' => '8523'],
    ['category' => 'economic_activity', 'name' => 'Establecimientos que combinan diferentes niveles de educación', 'alias' => null, 'code' => '8530'],
    ['category' => 'economic_activity', 'name' => 'Educación técnica profesional', 'alias' => null, 'code' => '8541'],
    ['category' => 'economic_activity', 'name' => 'Educación tecnológica', 'alias' => null, 'code' => '8542'],
    ['category' => 'economic_activity', 'name' => 'Educación de instituciones universitarias o de escuelas tecnológicas', 'alias' => null, 'code' => '8543'],
    ['category' => 'economic_activity', 'name' => 'Educación de universidades', 'alias' => null, 'code' => '8544'],
    ['category' => 'economic_activity', 'name' => 'Formación académica no formal', 'alias' => null, 'code' => '8551'],
    ['category' => 'economic_activity', 'name' => 'Enseñanza deportiva y recreativa', 'alias' => null, 'code' => '8552'],
    ['category' => 'economic_activity', 'name' => 'Enseñanza cultural', 'alias' => null, 'code' => '8553'],
    ['category' => 'economic_activity', 'name' => 'Otros tipos de educación n.c.p.', 'alias' => null, 'code' => '8559'],
    ['category' => 'economic_activity', 'name' => 'Actividades de apoyo a la educación', 'alias' => null, 'code' => '8560'],
    ['category' => 'economic_activity', 'name' => 'Actividades de hospitales y clínicas, con internación', 'alias' => null, 'code' => '8610'],
    ['category' => 'economic_activity', 'name' => 'Actividades de la práctica médica, sin internación', 'alias' => null, 'code' => '8621'],
    ['category' => 'economic_activity', 'name' => 'Actividades de la práctica odontológica', 'alias' => null, 'code' => '8622'],
    ['category' => 'economic_activity', 'name' => 'Actividades de apoyo diagnóstico', 'alias' => null, 'code' => '8691'],
    ['category' => 'economic_activity', 'name' => 'Actividades de apoyo terapéutico', 'alias' => null, 'code' => '8692'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades de atención de la salud humana', 'alias' => null, 'code' => '8699'],
    ['category' => 'economic_activity', 'name' => 'Actividades de atención residencial medicalizada de tipo general', 'alias' => null, 'code' => '8710'],
    ['category' => 'economic_activity', 'name' => 'Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas', 'alias' => null, 'code' => '8720'],
    ['category' => 'economic_activity', 'name' => 'Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas', 'alias' => null, 'code' => '8730'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades de atención en instituciones con alojamiento', 'alias' => null, 'code' => '8790'],
    ['category' => 'economic_activity', 'name' => 'Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas', 'alias' => null, 'code' => '8810'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades de asistencia social sin alojamiento', 'alias' => null, 'code' => '8890'],
    ['category' => 'economic_activity', 'name' => 'Creación literaria', 'alias' => null, 'code' => '9001'],
    ['category' => 'economic_activity', 'name' => 'Creación musical', 'alias' => null, 'code' => '9002'],
    ['category' => 'economic_activity', 'name' => 'Creación teatral', 'alias' => null, 'code' => '9003'],
    ['category' => 'economic_activity', 'name' => 'Creación audiovisual', 'alias' => null, 'code' => '9004'],
    ['category' => 'economic_activity', 'name' => 'Artes plásticas y visuales', 'alias' => null, 'code' => '9005'],
    ['category' => 'economic_activity', 'name' => 'Actividades teatrales', 'alias' => null, 'code' => '9006'],
    ['category' => 'economic_activity', 'name' => 'Actividades de espectáculos musicales en vivo', 'alias' => null, 'code' => '9007'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades de espectáculos en vivo', 'alias' => null, 'code' => '9008'],
    ['category' => 'economic_activity', 'name' => 'Actividades de bibliotecas y archivos', 'alias' => null, 'code' => '9101'],
    ['category' => 'economic_activity', 'name' => 'Actividades y funcionamiento de museos, conservación de edificios y sitios históricos', 'alias' => null, 'code' => '9102'],
    ['category' => 'economic_activity', 'name' => 'Actividades de jardines botánicos, zoológicos y reservas naturales', 'alias' => null, 'code' => '9103'],
    ['category' => 'economic_activity', 'name' => 'Actividades de juegos de azar y apuestas', 'alias' => null, 'code' => '9200'],
    ['category' => 'economic_activity', 'name' => 'Gestión de instalaciones deportivas', 'alias' => null, 'code' => '9311'],
    ['category' => 'economic_activity', 'name' => 'Actividades de clubes deportivos', 'alias' => null, 'code' => '9312'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades deportivas', 'alias' => null, 'code' => '9319'],
    ['category' => 'economic_activity', 'name' => 'Actividades de parques de atracciones y parques temáticos', 'alias' => null, 'code' => '9321'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades recreativas y de esparcimiento n.c.p.', 'alias' => null, 'code' => '9329'],
    ['category' => 'economic_activity', 'name' => 'Actividades de asociaciones empresariales y de empleadores', 'alias' => null, 'code' => '9411'],
    ['category' => 'economic_activity', 'name' => 'Actividades de asociaciones profesionales', 'alias' => null, 'code' => '9412'],
    ['category' => 'economic_activity', 'name' => 'Actividades de sindicatos de empleados', 'alias' => null, 'code' => '9420'],
    ['category' => 'economic_activity', 'name' => 'Actividades de asociaciones religiosas', 'alias' => null, 'code' => '9491'],
    ['category' => 'economic_activity', 'name' => 'Actividades de asociaciones políticas', 'alias' => null, 'code' => '9492'],
    ['category' => 'economic_activity', 'name' => 'Actividades de otras asociaciones n.c.p.', 'alias' => null, 'code' => '9499'],
    ['category' => 'economic_activity', 'name' => 'Mantenimiento y reparación de computadoras y de equipo periférico', 'alias' => null, 'code' => '9511'],
    ['category' => 'economic_activity', 'name' => 'Mantenimiento y reparación de equipos de comunicación', 'alias' => null, 'code' => '9512'],
    ['category' => 'economic_activity', 'name' => 'Mantenimiento y reparación de aparatos electrónicos de consumo', 'alias' => null, 'code' => '9521'],
    ['category' => 'economic_activity', 'name' => 'Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería', 'alias' => null, 'code' => '9522'],
    ['category' => 'economic_activity', 'name' => 'Reparación de calzado y artículos de cuero', 'alias' => null, 'code' => '9523'],
    ['category' => 'economic_activity', 'name' => 'Reparación de muebles y accesorios para el hogar', 'alias' => null, 'code' => '9524'],
    ['category' => 'economic_activity', 'name' => 'Mantenimiento y reparación de otros efectos personales y enseres domésticos', 'alias' => null, 'code' => '9529'],
    ['category' => 'economic_activity', 'name' => 'Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel', 'alias' => null, 'code' => '9601'],
    ['category' => 'economic_activity', 'name' => 'Peluquería y otros tratamientos de belleza', 'alias' => null, 'code' => '9602'],
    ['category' => 'economic_activity', 'name' => 'Pompas fúnebres y actividades relacionadas', 'alias' => null, 'code' => '9603'],
    ['category' => 'economic_activity', 'name' => 'Otras actividades de servicios personales n.c.p.', 'alias' => null, 'code' => '9609'],
    ['category' => 'economic_activity', 'name' => 'Actividades de los hogares individuales como empleadores de personal doméstico', 'alias' => null, 'code' => '9700'],
    ['category' => 'economic_activity', 'name' => 'Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio', 'alias' => null, 'code' => '9810'],
    ['category' => 'economic_activity', 'name' => 'Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio', 'alias' => null, 'code' => '9820'],
    ['category' => 'economic_activity', 'name' => 'Actividades de organizaciones y entidades extraterritoriales', 'alias' => null, 'code' => '9900'],
];
