<?php

return [
    ['category' => 'taxe_type', 'name' => 'Aporte especial para la administración de justicia', 'alias' => null, 'value' => null, 'code' => '1', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Gravamen a los movimientos financieros', 'alias' => null, 'value' => null, 'code' => '2', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Impuesto al Patrimonio', 'alias' => null, 'value' => null, 'code' => '3', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Impuesto sobre la renta y complementario régimen tributario especial', 'alias' => null, 'value' => null, 'code' => '4', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Impuesto sobre la renta y complementario régimen ordinario', 'alias' => 'Declarante de Renta', 'value' => null, 'code' => '5', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Ingresos y patrimonio', 'alias' => null, 'value' => null, 'code' => '6', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Retención en la fuente a título de renta', 'alias' => 'Agente de Retención en la Fuente', 'value' => null, 'code' => '7', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Retención timbre nacional', 'alias' => null, 'value' => null, 'code' => '8', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Retención en la fuente en el impuesto sobre las ventas', 'alias' => null, 'value' => null, 'code' => '9', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Obligado aduanero / Usuario Aduanero', 'alias' => null, 'value' => null, 'code' => '10', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],

    ['category' => 'taxe_type', 'name' => 'Gran contribuyente', 'alias' => null, 'value' => null, 'code' => '13', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Informante de exógena', 'alias' => null, 'value' => null, 'code' => '14', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Autorretenedor', 'alias' => null, 'value' => null, 'code' => '15', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Obligación de facturar por ingresos de bienes y/o servicios excluidos', 'alias' => null, 'value' => null, 'code' => '16', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Profesionales de compra y venta de divisas', 'alias' => null, 'value' => null, 'code' => '17', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Precios de Transferencia', 'alias' => null, 'value' => null, 'code' => '18', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Productor y/o exportador de bienes exentos', 'alias' => null, 'value' => null, 'code' => '19', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Obtención NIT', 'alias' => null, 'value' => null, 'code' => '20', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Declarar el ingreso o salida del país de divisas o moneda legal colombiana', 'alias' => null, 'value' => null, 'code' => '21', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Obligado a cumplir deberes formales a nombre de terceros', 'alias' => null, 'value' => null, 'code' => '22', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Agente de retención en el impuesto sobre las ventas', 'alias' => 'Agente de Retención IVA', 'value' => null, 'code' => '23', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],

    ['category' => 'taxe_type', 'name' => 'Declaración Informativa Individual Precios de transferencia', 'alias' => null, 'value' => null, 'code' => '26', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],

    ['category' => 'taxe_type', 'name' => 'Impuesto Nacional a la Gasolina y al ACPM', 'alias' => null, 'value' => null, 'code' => '32', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Impuesto Nacional a la consulta / consumo', 'alias' => null, 'value' => null, 'code' => '33', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Establecimiento Permanente', 'alias' => null, 'value' => null, 'code' => '36', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Proveedor de Servicios Tecnológicos PST', 'alias' => null, 'value' => null, 'code' => '39', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Declaración anual de activos en el exterior', 'alias' => null, 'value' => null, 'code' => '41', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Obligado a Llevar Contabilidad', 'alias' => null, 'value' => null, 'code' => '42', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Autorretenedor de rendimientos financieros', 'alias' => null, 'value' => null, 'code' => '45', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'IVA Prestadores de Servicios desde el Exterior', 'alias' => null, 'value' => null, 'code' => '46', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Régimen Simple de Tributación – SIMPLE', 'alias' => 'Régimen Simple', 'value' => null, 'code' => '47', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Impuesto sobre las ventas - IVA', 'alias' => 'Responsable de IVA', 'value' => null, 'code' => '48', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'No responsable de IVA', 'alias' => null, 'value' => null, 'code' => '49', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'No responsable de Consumo restaurantes y bares', 'alias' => null, 'value' => null, 'code' => '50', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Agente retención impoconsumo de bienes inmuebles', 'alias' => null, 'value' => null, 'code' => '51', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Facturador electrónico', 'alias' => 'Obligado Factura Electrónica', 'value' => null, 'code' => '52', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Persona Jurídica No Responsable de IVA', 'alias' => null, 'value' => null, 'code' => '53', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Intercambio Automático de Información CRS', 'alias' => null, 'value' => null, 'code' => '54', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Informante de Beneficiarios Finales', 'alias' => null, 'value' => null, 'code' => '55', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Impuesto al Carbono', 'alias' => null, 'value' => null, 'code' => '56', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Intercambio Automático de Información FATCA', 'alias' => null, 'value' => null, 'code' => '58', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Autorretención especial renta', 'alias' => null, 'value' => null, 'code' => '59', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Autorretención por concepto de intereses y rendimientos financieros de entidades vigiladas por la SFC', 'alias' => null, 'value' => null, 'code' => '60', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
    ['category' => 'taxe_type', 'name' => 'Autorretención por concepto de comisiones de entidades vigiladas por la SFC', 'alias' => null, 'value' => null, 'code' => '61', 'icon' => null, 'is_active' => true, 'lang' => 'ES'],
];
